handle    = "Diana"
port      = [5014, 5014]     # lokaler UDP-Port 5014
whoisport = 4000
autoreply = "Bin gleich zurÃ¼ck."
imagepath = "images"

[colors]
Alice    = "RED"
Bob      = "GREEN"
Caroline = "BLUE"
Diana    = "MAGENTA"

#python3 discovery_main.py diana.toml 9000 \
#  > logs/diana.discovery.log 2>&1 &
#
#python3 network_main.py   diana.toml 9001 \
#  > logs/diana.network.log   2>&1 &
#
#python3 main_ui.py diana.toml 9000 9001
#